export type Attendance = {
  id: string;
  employeeId: string;
  fullName: string;
  employeeCode: string;
  workDate: string;
  clockIn: string | null;
  clockOut: string | null;
  clockInMethod: string | null;
  clockOutMethod: string | null;
  workedMinutes: number | null;
  overtimeMinutes: number | null;
  status: string;
  updatedAt: string;
};
export type CorrectionRequest = {
  id: string;
  companyId: string;
  employeeId: string;
  attendanceId: string;
  requestedBy: string;
  fullName: string;
  employeeCode: string;
  salaryType: string;
  workDate: string;
  originalClockIn: string | null;
  originalClockOut: string | null;
  originalClockInMethod: string | null;
  originalClockOutMethod: string | null;
  originalStatus: string;
  originalWorkedMinutes: number | null;
  originalOvertimeMinutes: number | null;
  originalUpdatedAt: string;
  proposedClockIn: string;
  proposedClockOut: string;
  reason: string;
  status: "pending" | "approved" | "rejected";
  reviewedBy: string | null;
  reviewedAt: string | null;
  rejectionReason: string | null;
  createdAt: string;
  stale: number;
  currentClockIn: string | null;
  currentClockOut: string | null;
};
export type CorrectionResult = { ok: string } | { error: string };
export type PayrollPeriod = {
  id: string;
  period: string;
  periodStart: string;
  periodEnd: string;
  status: string;
};
